#!/usr/bin/env python3
"""
Demo Backtest Runner for ai-trader
Simulates a multi-trade historical execution run using BacktestEngine.
"""

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.models.schemas import HistoricalBar, TradeSignal, SignalAction
from src.engine.backtest import BacktestEngine


def main():
    print("=" * 65)
    print(" 🚀 RUNNING AI-TRADER DEMO BACKTEST SIMULATION (1,000 USD CAPITAL)")
    print("=" * 65)

    # 1. Historical OHLCV Bar Data (Simulated 10-day market movement for TSLA)
    raw_bars = [
        # Day 1: Entry setup around $200
        {"ts": "2026-07-01", "o": 200.0, "h": 202.0, "l": 198.0, "c": 201.0, "v": 50000},
        # Day 2: Price moves up to $210 (Hits Take Profit at $208)
        {"ts": "2026-07-02", "o": 201.0, "h": 210.0, "l": 200.5, "c": 209.0, "v": 75000},
        # Day 3: Market consolidates
        {"ts": "2026-07-03", "o": 209.0, "h": 211.0, "l": 207.0, "c": 208.5, "v": 40000},
        # Day 4: New Signal Entry around $208
        {"ts": "2026-07-04", "o": 208.5, "h": 215.0, "l": 208.0, "c": 214.0, "v": 60000},
        # Day 5: Hits Take Profit at $218
        {"ts": "2026-07-05", "o": 214.0, "h": 220.0, "l": 213.0, "c": 219.0, "v": 80000},
        # Day 6: Pullback entry
        {"ts": "2026-07-06", "o": 219.0, "h": 221.0, "l": 215.0, "c": 216.0, "v": 55000},
        # Day 7: Market drop -> Hits Stop Loss at $210
        {"ts": "2026-07-07", "o": 216.0, "h": 216.5, "l": 208.0, "c": 209.0, "v": 90000},
        # Day 8: Recovery signal
        {"ts": "2026-07-08", "o": 209.0, "h": 214.0, "l": 208.5, "c": 213.0, "v": 65000},
        # Day 9: Price surge -> Hits Take Profit at $222
        {"ts": "2026-07-09", "o": 213.0, "h": 225.0, "l": 212.5, "c": 224.0, "v": 100000},
        # Day 10: Final close
        {"ts": "2026-07-10", "o": 224.0, "h": 226.0, "l": 222.0, "c": 225.0, "v": 45000},
    ]

    bars = [
        HistoricalBar(
            timestamp=b["ts"], open=b["o"], high=b["h"], low=b["l"], close=b["c"], volume=b["v"]
        )
        for b in raw_bars
    ]

    # 2. Strategy Signals generated by LLM Council / Technical Engine
    signals = [
        TradeSignal(
            ticker="TSLA",
            action=SignalAction.BUY,
            confidence_score=88.0,
            stop_loss=195.0,
            take_profit=208.0,
            reasoning_thesis="Breakout above 200 resistance on positive EV battery news",
            invalidation_criteria="Drop below 195",
            advisor_model="Claude-3.5-Sonnet"
        ),
        TradeSignal(
            ticker="TSLA",
            action=SignalAction.BUY,
            confidence_score=82.0,
            stop_loss=204.0,
            take_profit=218.0,
            reasoning_thesis="Moving average 15-min trend continuation",
            invalidation_criteria="Drop below 204",
            advisor_model="GPT-4o"
        ),
        TradeSignal(
            ticker="TSLA",
            action=SignalAction.BUY,
            confidence_score=75.0,
            stop_loss=210.0,
            take_profit=225.0,
            reasoning_thesis="Momentum buy at pullback",
            invalidation_criteria="Drop below 210",
            advisor_model="Gemini-Auditor"
        ),
        TradeSignal(
            ticker="TSLA",
            action=SignalAction.BUY,
            confidence_score=91.0,
            stop_loss=206.0,
            take_profit=222.0,
            reasoning_thesis="Strong volume accumulation signal",
            invalidation_criteria="Drop below 206",
            advisor_model="Consensus-Council"
        ),
    ]

    # 3. Run Simulation
    engine = BacktestEngine()
    starting_capital = 1000.0
    result = engine.run_simulation(
        ticker="TSLA",
        starting_capital=starting_capital,
        bars=bars,
        signals=signals
    )

    # 4. Print Formatted Results
    print(f"\n📊 TICKER: {result.ticker}")
    print(f"💰 Starting Capital:  ${result.starting_capital:,.2f} USD")
    print(f"💵 Ending Capital:    ${result.ending_capital:,.2f} USD")
    print(f"📈 Total Return:      {result.total_return_pct:+.2f}%")
    print(f"🎯 Win Rate:          {result.win_rate_pct:.1f}% ({result.winning_trades} Wins / {result.losing_trades} Losses)")
    print(f"📉 Max Drawdown:      {result.max_drawdown_pct:.2f}%")
    print(f"⚖️ Profit Factor:     {result.profit_factor:.2f}")

    print("\n📜 EXECUTED TRADES LOG:")
    print("-" * 65)
    for idx, trade in enumerate(result.executed_trades, 1):
        status_icon = "✅" if trade.pnl > 0 else "❌"
        print(
            f"Trade #{idx} {status_icon} | Action: {trade.action.value} | Entry: ${trade.entry_price:.2f} "
            f"| Exit: ${trade.exit_price:.2f} ({trade.exit_reason}) | PnL: ${trade.pnl:+.2f} ({trade.pnl_pct:+.2f}%)"
        )
    print("-" * 65)


if __name__ == "__main__":
    main()
